name: Sensor Monitoring

on:
  push:
    branches:
      - main  # `main` ブランチへのプッシュ時に実行

jobs:
  monitor:
    runs-on: ubuntu-latest  # Ubuntu 上で実行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: sudo apt-get install -y iproute2 procps net-tools

      - name: Run Sensor Monitoring Script
        run: |
          chmod +x ./process-connect-dest.sh  # 実行権限を付与
          ./process-connect-dest.sh
