name: Run Shell Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up the script to run
      run: |
        chmod +x ./process-traffic.sh
    
    - name: Run the shell script
      run: |
        ./process-traffic.sh
